name: 'Publish page'
on:
  push:
    branches:
      - fork
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
      - name: Download dependencies
        run: bun install --frozen-lockfile
      - name: Build project
        run: bun run build
      - name: Upload built artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/
          name: unduck
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: unduck
